<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    static public function countries()
    {
        $currencies = [
            'USD' => 'United States',
            'AED' => 'United Arab Emirates',
            // 'AFN' => 'Afghanistan',
            'AMD' => 'Armenia',
            // 'ANG' => 'Netherlands',
            // 'AOA' => 'Angola',
            'ARS' => 'Argentina',
            'AUD' => 'Australia',
            // 'AWG' => 'Aruba',
            'AZN' => 'Azerbaijan',
            'BAM' => 'Bosnia',
            // 'BBD' => 'Barbados',
            'BDT' => 'Bangladesh',
            'BGN' => 'Bulgaria',
            // 'BIF' => 'Burundi',
            'BMD' => 'Bermuda',
            // 'BND' => 'Brunei',
            'BOB' => 'Bolivia',
            'BRL' => 'Brazil',
            // 'BSD' => 'Bahamas',
            // 'BWP' => 'Botswana',
            'BYN' => 'Belarus',
            // 'BZD' => 'Belize',
            'CAD' => 'Canada',
            // 'CDF' => 'Congo',
            'CHF' => 'Switzerland',
            'CLP' => 'Chile',
            'CNY' => 'China',
            'COP' => 'Colombia',
            'CRC' => 'Costa Rica',
            // 'CVE' => 'Cabo Verde',
            'CZK' => 'Czech Republic',
            // 'DJF' => 'Djibouti',
            'DKK' => 'Denmark',
            'DOP' => 'Dominican Republic',
            'DZD' => 'Algeria',
            'EGP' => 'Egypt',
            // 'ETB' => 'Ethiopia',
            'EUR' => 'European Union',
            // 'FJD' => 'Fiji',
            // 'FKP' => 'Falkland',
            'GBP' => 'United Kingdom',
            'GEL' => 'Georgia',
            // 'GIP' => 'Gibraltar',
            // 'GMD' => 'Gambian',
            // 'GNF' => 'Guinea',
            'GTQ' => 'Guatemala',
            // 'GYD' => 'Guyana',
            'HKD' => 'Hong Kong',
            'HNL' => 'Honduras',
            'HRK' => 'Croatia',
            // 'HTG' => 'Haiti',
            'HUF' => 'Hungary',
            'IDR' => 'Indonesia',
            'ILS' => 'Israel',
            'INR' => 'India',
            'ISK' => 'Iceland',
            'JMD' => 'Jamaica',
            'JPY' => 'Japan',
            'KES' => 'Kenya',
            'KGS' => 'Kyrgyzstan',
            'KHR' => 'Cambodia',
            // 'KMF' => 'Comoros',
            'KRW' => 'South Korea',
            // 'KYD' => 'Islands',
            'KZT' => 'Kazakhstan',
            // 'LAK' => 'Laos',
            'LBP' => 'Lebanon',
            'LKR' => 'Sri Lankan',
            // 'LRD' => 'Liberia',
            // 'LSL' => 'Lesotho',
            'MAD' => 'Morocco',
            'MDL' => 'Moldova',
            // 'MGA' => 'Madagascar',
            'MKD' => 'Macedonia',
            'MMK' => 'Myanmar',
            'MNT' => 'Mongolia',
            // 'MOP' => 'Macau',
            // 'MRO' => 'Mauritania',
            'MUR' => 'Mauritius',
            'MVR' => 'Maldives',
            // 'MWK' => 'Malawi',
            'MXN' => 'Mexico',
            'MYR' => 'Malaysian',
            // 'MZN' => 'Mozambique',
            'NAD' => 'Namibia',
            'NGN' => 'Nigeria',
            'NIO' => 'Nicaragua',
            'NOK' => 'Norway',
            'NPR' => 'Nepal',
            'NZD' => 'New Zealand',
            'PAB' => 'Panama',
            'PEN' => 'Peru',
            // 'PGK' => 'Papua New Guinea',
            'PHP' => 'Philippines',
            'PKR' => 'Pakistan',
            'PLN' => 'Poland',
            // 'PYG' => 'Paraguay',
            'QAR' => 'Qatar',
            'RON' => 'Romania',
            'RSD' => 'Serbia',
            'RUB' => 'Russia',
            // 'RWF' => 'Rwanda',
            'SAR' => 'Saudi Arabia',
            // 'SBD' => 'Solomon Islands',
            // 'SCR' => 'Seychelles',
            'SEK' => 'Sweden',
            'SGD' => 'Singapore',
            // 'SHP' => 'Saint Helena and Ascension',
            // 'SLL' => 'Sierra Leone',
            // 'SOS' => 'Somalia',
            // 'SRD' => 'Suriname',
            // 'STD' => 'Sao Tome & Principe',
            // 'SZL' => 'Swaziland',
            'THB' => 'Thailand',
            // 'TJS' => 'Tajikistan',
            // 'TOP' => 'Liechtenstein',
            'TRY' => 'Turky',
            'TTD' => 'Trinidad and Tobago',
            'TWD' => 'Taiwan',
            // 'TZS' => 'Tanzania',
            'UAH' => 'Ukraine',
            'UGX' => 'Uganda',
            'UYU' => 'Uruguay',
            'UZS' => 'Uzbekistan',
            'VND' => 'Vietnam',
            // 'VUV' => 'Vanuatu',
            // 'WST' => 'Samoa',
            // 'XPF' => 'Polynesia',
            // 'YER' => 'Yemen',
            'ZAR' => 'South Africa',
            // 'ZMW' => 'Zambia'
        ];

        return $currencies;
    }
}
